name = "ant"
title = "Ant"
version = "0.0.0-2"

[description]
summary = "Ant colony shared library"
keywords = []

[author]
name = "sourcetrait"
title = "SourceTrait"
email = "development@sourcetrait.com"

[license]
spdx = "agpl3"
file = "LICENSE-AGPL-3.txt"

[provider]
name = "github"

[dependencies]
equip = { author = "sourcetrait", version = "0", provider = "github", path = "../equip" }
empower = { author = "sourcetrait", version = "0", provider = "github", path = "../empower" }
