use crate::*;

impl NuSh {
    /// What: assembles the `ToolRouter` from the per-tool router
    /// functions generated by each `#[mcp::tool_router(router = ...)]`
    /// block, OMITTING operator-denied tools (`config().deny`). The
    /// core four (info, inspect, processes, kill) always register.
    ///
    /// Why: deny at router assembly means a denied tool is absent from
    /// tools/list entirely -- no schema tokens in the agent's context,
    /// no denied-error loop; a call anyway fails at the rmcp layer as
    /// an unknown tool. Assembly is runtime `+` composition, so the
    /// conditional surface costs nothing. `#[mcp::tool_handler(router =
    /// self.tool_router)]` (below) dispatches off the instance field
    /// `NuSh::new` stores this into.
    ///
    /// Where: called by `NuSh::new`; read per-request through the
    /// generated `ServerHandler::call_tool` / `list_tools`.
    pub(crate) fn tool_router() -> mcp::ToolRouter<Self> {
        let deny = &config().deny;
        let mut router = Self::processes_router()
            + Self::kill_router()
            + Self::info_router()
            + Self::inspect_router();
        if !deny.denies(DeniableTool::Run) {
            router = router + Self::run_router();
        }
        if !deny.denies(DeniableTool::Rerun) {
            router = router + Self::rerun_router();
        }
        if !deny.denies(DeniableTool::Interact) {
            router = router + Self::interact_router();
        }
        if !deny.denies(DeniableTool::Call) {
            router = router + Self::call_router();
        }
        if !deny.denies(DeniableTool::Learn) {
            router = router + Self::learn_router();
        }
        if !deny.denies(DeniableTool::New) {
            router = router + Self::new_router();
        }
        if !deny.denies(DeniableTool::Commit) {
            router = router + Self::commit_router();
        }
        if !deny.denies(DeniableTool::Library) {
            router = router + Self::library_router();
        }
        router
    }
}

#[mcp::tool_handler(router = self.tool_router)]
impl mcp::ServerHandler for NuSh {
    fn get_info(&self) -> mcp::ServerInfo {
        // Per [[rmcp-implementation-from-build-env-gotcha]]: must construct
        // Implementation via env! in THIS crate's source so the macros expand
        // against our CARGO_PKG_*, not rmcp's.
        //
        // ServerCapabilities::default() does NOT include `tools: Some(...)` --
        // empirically confirmed 2026-05-31 when Claude Code's MCP client
        // skipped tools/list after restart because the initialize response
        // advertised no tool capability. Explicit `.enable_tools()` is
        // required for the client to discover our tool surface.
        let id = &config().id;
        let namespace = &config().namespace;
        // Title carries the namespace when non-default so co-running store
        // variants stay tellable-apart in the client's /mcp listing.
        let title = if namespace == "default" {
            "nushell".to_string()
        } else {
            format!("nushell ({namespace})")
        };
        let mut info = mcp::ServerInfo::default();
        info.capabilities = mcp::ServerCapabilities::builder().enable_tools().build();
        info.server_info = mcp::Implementation::new(
            lib_empower::consts::NUSHELL_MCP,
            env!("CARGO_PKG_VERSION"),
        )
        .with_title(title);
        info.instructions = Some(format!(
            "Evaluation artifacts are cached at \
             $XDG_CACHE_HOME/sourcetrait/nushell_mcp/{id}/{namespace}/{{runs,interacts,calls}}/<nonce>/{{stdout,stderr}}; \
             closures cached at \
             $XDG_CACHE_HOME/sourcetrait/nushell_mcp/{id}/{namespace}/closures/<rerun_id>.json. \
             Registered libraries live in a signed git repo at \
             $XDG_DATA_HOME/sourcetrait/nushell_mcp/{id}/{namespace}/libraries/; signing keypair at \
             $XDG_DATA_HOME/sourcetrait/nushell_mcp/{id}/{namespace}/keypair/. \
             This server's state coordinate: id `{id}`, namespace `{namespace}`.",
        ));
        info
    }
}
