use crate::*;

impl NuSh {
    /// What: assembles the full `ToolRouter` from the per-tool router
    /// functions generated by each `#[mcp::tool_router(router = ...)]`
    /// block across the `server::tool::*` modules.
    ///
    /// Why: the tool surface is split one-file-per-tool; rmcp's
    /// `ToolRouter` composes with `+`, so each module contributes its
    /// single-tool router and this sum is the canonical combined
    /// router. `#[mcp::tool_handler]` (below) defaults its dispatch to
    /// `Self::tool_router()`, and `NuSh::new` stores the same value in
    /// the (otherwise dead) `tool_router` field.
    ///
    /// Where: called by the generated `ServerHandler::call_tool` /
    /// `list_tools` (via the `#[tool_handler]` default router expr) and
    /// by `NuSh::new`.
    pub(crate) fn tool_router() -> mcp::ToolRouter<Self> {
        Self::run_router()
            + Self::interact_router()
            + Self::call_router()
            + Self::rerun_router()
            + Self::processes_router()
            + Self::kill_router()
            + Self::info_router()
            + Self::learn_router()
            + Self::new_router()
            + Self::commit_router()
            + Self::library_router()
            + Self::inspect_router()
    }
}

#[mcp::tool_handler]
impl mcp::ServerHandler for NuSh {
    fn get_info(&self) -> mcp::ServerInfo {
        // Per [[rmcp-implementation-from-build-env-gotcha]]: must construct
        // Implementation via env! in THIS crate's source so the macros expand
        // against our CARGO_PKG_*, not rmcp's.
        //
        // ServerCapabilities::default() does NOT include `tools: Some(...)` --
        // empirically confirmed 2026-05-31 when Claude Code's MCP client
        // skipped tools/list after restart because the initialize response
        // advertised no tool capability. Explicit `.enable_tools()` is
        // required for the client to discover our tool surface.
        let mut info = mcp::ServerInfo::default();
        info.capabilities = mcp::ServerCapabilities::builder().enable_tools().build();
        info.server_info =
            mcp::Implementation::new(build_target().name(), env!("CARGO_PKG_VERSION")).with_title(
                match build_target() {
                    BuildTarget::Main => "nushell",
                    BuildTarget::Test => "nushell (test)",
                },
            );
        info.instructions = Some(
            "Evaluation artifacts are cached at \
             $XDG_CACHE_HOME/sourcetrait/nushell_mcp/{runs,interacts,calls}/<nonce>/{stdout,stderr}; \
             closures cached at $XDG_CACHE_HOME/sourcetrait/nushell_mcp/closures/<rerun_id>.json. \
             Registered libraries live in a signed git repo at \
             $XDG_DATA_HOME/sourcetrait/nushell_mcp/libraries/; signing keypair at \
             $XDG_DATA_HOME/sourcetrait/nushell_mcp/keypair/."
                .to_string(),
        );
        info
    }
}
