name = "empower"
tile = "Empower"
version = "0.0.0-2"

[author]
name = "sourcetrait"
title = "SourceTrait"
email = "development@sourcetrait.com"

[provider]
name = "github"

libraries = [
    "ant",
    "drone",
    "empower",
    "fae",
    "queen"
]

[dev]
libraries = []

