name = "empwr"
tile = "empwr"
version = "0.0.1"

[author]
name = "sourcetrait"
title = "SourceTrait"
email = "development@sourcetrait.com"

[provider]
name = "github"

[desk]
gear = [
    "empwr"
]

[box]
gear = [
    "empwr"
]