[workspace]
resolver = "2"
members = [
  "crates/sourcetrait_lib_empower",
  "crates/sourcetrait_cmdlib_empower",
  "crates/nu_plugin_empower",
]

[workspace.dependencies]
chrono = { version = "0.4" }
clap = { version = "4", features = ["derive"] }
derive_builder = { version = "0.20" }
directories = { version = "6" }
hek = { version = "0.5" }
nu-plugin = { version = "0.113" }
nu-protocol = { version = "0.113" }
regex = { version = "1" }
serde = { version = "1", features = ["derive"] }
shellexpand = { version = "3", features = ["path"] }
snafu = "0.8"
sourcetrait_chronox = { version = "1" }
sourcetrait_clapx = { version = "1" }
sourcetrait_cmdlib_empower = { path = "crates/sourcetrait_cmdlib_empower" }
sourcetrait_lib_empower = { path = "crates/sourcetrait_lib_empower" }
sourcetrait_ronx = { version = "3" }
sourcetrait_stdx = { version = "1" }
sourcetrait_testing = { version = "4" }
sourcetrait_tomlx = { version = "3" }
strum = { version = "0.27", features = ["derive"] }
tempfile = { version = "3.20" }
toml = { version = "0.8" }
