name = "queen"
title = "Queen"
version = "0.0.0-2"

[nushell]
version = "0.113.1"

[description]
summary = "Queen role library"
keywords = []

[author]
name = "sourcetrait"
title = "SourceTrait"
email = "development@sourcetrait.com"

[license]
spdx = "agpl3"
file = "LICENSE-AGPL-3.txt"

[provider]
name = "github"

[dependencies]
equip = { author = "sourcetrait", version = "0", provider = "github", path = "../equip" }
empower = { author = "sourcetrait", version = "0", provider = "github", path = "../empower" }
ant = { author = "sourcetrait", version = "0", provider = "github", path = "../ant" }
