[package]
name = "nu_sh_mcp"
version = "0.0.26"
edition = "2024"
description = "Nushell-engine MCP server for sourcetrait_empower"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_empower"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "empower", "nushell", "mcp"]

[[bin]]
name = "nu_sh_mcp"
path = "src/main.rs"

[[bin]]
name = "nu_sh_mcp_worker"
path = "src/bin/nu_sh_mcp_worker.rs"

[dependencies]
clap.workspace = true
directories.workspace = true
nix.workspace = true
nu-cmd-lang.workspace = true
nu-command.workspace = true
nu-engine.workspace = true
nu-json.workspace = true
nu-parser.workspace = true
nu-path.workspace = true
nu-plugin-engine.workspace = true
nu-protocol.workspace = true
nuon.workspace = true
rmcp.workspace = true
rmp-serde.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sourcetrait_lib_empower.workspace = true
tokio.workspace = true

[dev-dependencies]
sourcetrait_testing.workspace = true
tempfile.workspace = true
