[package]
name = "sourcetrait_equipment"
version = "0.0.0-1"
edition = "2024"
description = "Equipment model"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_ai_empower"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "equipment"]

[dependencies]
serde.workspace = true
snafu.workspace = true
semver.workspace = true

[dev-dependencies]
sourcetrait_testing.workspace = true
