"""rustdoc_overlay.py — OPTIONAL semantic overlay (degradation-first).

The floor (rustscan + characterize + emit) produces a correct, honest artifact alone. This
overlay only makes it BETTER, and only when a nightly toolchain and a buildable project are
present. It cannot run in an offline container with no cargo — by design it then no-ops with
an explicit banner, and the floor proceeds unchanged.

What the overlay adds when available:
  - Post-macro-expansion ground truth: the real count and identity of items generated by a
    registration macro (e.g. each command a `bind_command!` expands to), resolving the
    `expansion_unverified` counts the floor can only estimate from call-site arguments.
  - Re-export identity: what a `pub use` actually points at.
  - A reconciliation report: where the floor (which over-trusts source text) and rustdoc
    (which over-trusts the compiler, losing spans for re-exports / blanket / synthesized /
    macro items) DISAGREE — disagreement is itself a seam signal worth surfacing.

rustdoc JSON is nightly-only and format_version-gated; spans are null for re-exports,
blanket/synthesized impls, and macro-generated items. Null spans are FLAGGED, never dropped.
"""

from __future__ import annotations
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

# Format versions this overlay has been written against. If the toolchain emits a different
# version, we degrade rather than risk misreading the schema. Verified through 57 (nightly
# 2026-05-15); reconcile() handles the format-57 rename of `trait.name` to `trait.path` by
# accepting either key. Re-verify the impl/use/import shapes when extending past 57.
KNOWN_FORMAT_VERSIONS = set(range(26, 58))

# Standard-library blanket / auto-impl traits. The compiler synthesizes these for every type
# satisfying their bounds, so they ALWAYS land in the disagreement list under the naive logic
# (the source-text scanner cannot see compiler-synthesized impls). They confirm std coverage,
# NOT a user-macro-registration seam. We split them off into a separate informational
# disagreement entry so the loud `impls_only_in_rustdoc` signal surfaces only user-domain
# macro registration (derive macros, attribute macros, registration!() expansions).
STD_BLANKET_TRAITS = frozenset({
    "Any", "Borrow", "BorrowMut", "CloneToUninit", "Freeze", "From", "Into",
    "Receiver", "RefUnwindSafe", "Send", "Sized", "Sync", "ToOwned", "ToString",
    "TryFrom", "TryInto", "Unpin", "UnsafeUnpin", "UnwindSafe",
})


def toolchain_available():
    """Return (ok, reason). ok=False means degrade to floor-only."""
    if shutil.which("cargo") is None:
        return False, "cargo not found on PATH"
    try:
        r = subprocess.run(["cargo", "+nightly", "--version"],
                           capture_output=True, text=True, timeout=20)
        if r.returncode != 0:
            return False, "nightly toolchain not installed (cargo +nightly failed)"
    except Exception as e:
        return False, f"cargo invocation failed: {e}"
    return True, "ok"


def run_rustdoc_json(root: Path, package: str | None):
    """Invoke nightly rustdoc JSON. Returns parsed dict or raises. THIS SHELLS OUT (the only
    phase permitted to) and requires network/toolchain — untested in the offline container."""
    cmd = ["cargo", "+nightly", "rustdoc"]
    if package:
        cmd += ["-p", package]
    # rustdoc's extra-args (after `--`) require a single target filter when the package
    # has multiple targets (lib + bin(s)); cargo rejects with error 101 otherwise. Default
    # to --lib since rustdoc-JSON is overwhelmingly the library surface. Bin-only packages
    # will need a caller-side fork to specify --bin NAME.
    cmd += ["--lib", "--", "-Z", "unstable-options", "--output-format", "json"]
    # Override RUSTDOCFLAGS to cap-lints-allow so strict-doc projects (iced ships with
    # `-F rustdoc::broken-intra-doc-links` enabled) don't error out the rustdoc build
    # before the JSON gets written. Doesn't change any source-level warnings; only loosens
    # the overlay-time rustdoc lint gate.
    env = os.environ.copy()
    env["RUSTDOCFLAGS"] = "--cap-lints allow"
    subprocess.run(cmd, cwd=str(root), check=True, capture_output=True, text=True,
                   timeout=900, env=env)
    # rustdoc writes target/doc/<crate>.json
    docdir = root / "target" / "doc"
    candidates = sorted(docdir.glob("*.json"))
    if not candidates:
        raise FileNotFoundError("no rustdoc JSON produced")
    return json.loads(candidates[-1].read_text())


def reconcile(floor_facts: dict, rustdoc: dict):
    """Compare floor facts to rustdoc JSON. Returns an overlay dict: resolved macro-generated
    items, re-export targets, null-span flags, and floor/rustdoc disagreements."""
    fv = rustdoc.get("format_version")
    if fv not in KNOWN_FORMAT_VERSIONS:
        return {"status": "degraded",
                "reason": f"unrecognised rustdoc format_version={fv}; not reconciling"}
    index = rustdoc.get("index", {})
    overlay = {"status": "ok", "format_version": fv,
               "macro_generated": [], "reexports": [], "null_span_items": [],
               "disagreements": []}

    floor_impl_types = {(i.get("trait"), i.get("type")) for i in floor_facts.get("impls", [])}
    for item_id, item in index.items():
        name = item.get("name")
        span = item.get("span")  # null for re-exports/blanket/synthesized/macro items
        inner = item.get("inner", {})
        kind = next(iter(inner.keys()), None) if isinstance(inner, dict) else None
        if span is None and name:
            overlay["null_span_items"].append({"name": name, "kind": kind})
        if kind == "impl" and isinstance(inner.get("impl"), dict):
            tr = inner["impl"].get("trait")
            # rustdoc JSON < ~v45 used `trait.name`; format 57 renamed the field to
            # `trait.path` (still the bare name; full paths sit under inner["impl"]
            # elsewhere). Accept either key so the overlay survives the rename.
            tr_name = (tr.get("path") or tr.get("name")) if isinstance(tr, dict) else None
            if span is None and tr_name:
                # impl with no span => blanket / synthesized / macro-generated
                overlay["macro_generated"].append({"trait": tr_name, "span": None,
                                                    "note": "no span (blanket/synth/macro)"})
        if kind == "use" or kind == "import":
            tgt = inner.get(kind, {})
            overlay["reexports"].append({"name": name,
                                         "source": tgt.get("source") if isinstance(tgt, dict) else None})

    # Disagreement: items rustdoc has that the floor's impl set lacks. Split into
    # std-blanket-coverage (informational; compiler synthesizes these for every type
    # satisfying the bounds) and user-domain macro generation (the real signal -- a
    # derive macro, attribute macro, or reg_macro!() expansion landed an impl that the
    # source scanner could not see).
    rustdoc_impl_traits = {it["trait"] for it in overlay["macro_generated"] if it.get("trait")}
    floor_traits = {t for t, _ in floor_impl_types if t}
    only_rustdoc = sorted(rustdoc_impl_traits - floor_traits)
    std_blanket = sorted(t for t in only_rustdoc if t in STD_BLANKET_TRAITS)
    user_macro = sorted(t for t in only_rustdoc if t not in STD_BLANKET_TRAITS)
    if std_blanket:
        overlay["disagreements"].append({
            "kind": "std_blanket_coverage",
            "traits": std_blanket,
            "note": "Standard-library blanket / auto-impl coverage (Any/Send/Sync/From/Into/"
                    "etc.) that the source-text scanner cannot see. Compiler-synthesized; "
                    "NOT a user-macro-registration seam. Informational.",
        })
    if user_macro:
        overlay["disagreements"].append({
            "kind": "impls_only_in_rustdoc",
            "traits": user_macro,
            "note": "rustdoc sees impls the source scanner did not -- likely user-domain "
                    "macro-generated. Confirms a macro-registration seam (derive macros, "
                    "attribute macros, or registration!() expansions). Verify by reading "
                    "the macro invocation sites in reference.md.",
        })
    return overlay


def main():
    if len(sys.argv) < 2:
        print("usage: rustdoc_overlay.py <repo_root> [orientation_dir] [package]",
              file=sys.stderr)
        return 2
    root = Path(sys.argv[1]).resolve()
    odir = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else root / ".orientation"
    package = sys.argv[3] if len(sys.argv) > 3 else None

    ok, reason = toolchain_available()
    if not ok:
        banner = {"status": "absent", "reason": reason,
                  "effect": "Floor-only artifact. Macro-expansion counts remain "
                            "`expansion_unverified`; re-export targets unresolved. This is a "
                            "correct, honest artifact — just without the semantic overlay."}
        (odir / "rustdoc_overlay.json").write_text(json.dumps(banner, indent=2))
        print(f"[overlay] DEGRADED: {reason}")
        print("[overlay] floor-only artifact stands; no overlay applied.")
        return 0

    try:
        facts = json.loads((odir / "facts.json").read_text())
        rd = run_rustdoc_json(root, package)
        overlay = reconcile(facts, rd)
    except Exception as e:
        banner = {"status": "error", "reason": str(e),
                  "effect": "Floor-only artifact stands."}
        (odir / "rustdoc_overlay.json").write_text(json.dumps(banner, indent=2))
        print(f"[overlay] ERROR ({e}); floor-only artifact stands.")
        return 0

    (odir / "rustdoc_overlay.json").write_text(json.dumps(overlay, indent=2))
    print(f"[overlay] applied (format_version={overlay.get('format_version')}); "
          f"{len(overlay.get('macro_generated', []))} macro/blanket items, "
          f"{len(overlay.get('disagreements', []))} disagreement(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
