"""rustdoc_overlay.py — OPTIONAL semantic overlay (degradation-first).

The floor (rustscan + characterize + emit) produces a correct, honest artifact alone. This
overlay only makes it BETTER, and only when a nightly toolchain and a buildable project are
present. It cannot run in an offline container with no cargo — by design it then no-ops with
an explicit banner, and the floor proceeds unchanged.

What the overlay adds when available:
  - Post-macro-expansion ground truth: the real count and identity of items generated by a
    registration macro (e.g. each command a `bind_command!` expands to), resolving the
    `expansion_unverified` counts the floor can only estimate from call-site arguments.
  - Re-export identity: what a `pub use` actually points at.
  - A reconciliation report: where the floor (which over-trusts source text) and rustdoc
    (which over-trusts the compiler, losing spans for re-exports / blanket / synthesized /
    macro items) DISAGREE — disagreement is itself a seam signal worth surfacing.

rustdoc JSON is nightly-only and format_version-gated; spans are null for re-exports,
blanket/synthesized impls, and macro-generated items. Null spans are FLAGGED, never dropped.
"""

from __future__ import annotations
import json
import shutil
import subprocess
import sys
from pathlib import Path

# Format versions this overlay has been written against. If the toolchain emits a different
# version, we degrade rather than risk misreading the schema.
KNOWN_FORMAT_VERSIONS = {26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40}


def toolchain_available():
    """Return (ok, reason). ok=False means degrade to floor-only."""
    if shutil.which("cargo") is None:
        return False, "cargo not found on PATH"
    try:
        r = subprocess.run(["cargo", "+nightly", "--version"],
                           capture_output=True, text=True, timeout=20)
        if r.returncode != 0:
            return False, "nightly toolchain not installed (cargo +nightly failed)"
    except Exception as e:
        return False, f"cargo invocation failed: {e}"
    return True, "ok"


def run_rustdoc_json(root: Path, package: str | None):
    """Invoke nightly rustdoc JSON. Returns parsed dict or raises. THIS SHELLS OUT (the only
    phase permitted to) and requires network/toolchain — untested in the offline container."""
    cmd = ["cargo", "+nightly", "rustdoc"]
    if package:
        cmd += ["-p", package]
    cmd += ["--", "-Z", "unstable-options", "--output-format", "json"]
    subprocess.run(cmd, cwd=str(root), check=True, capture_output=True, text=True, timeout=900)
    # rustdoc writes target/doc/<crate>.json
    docdir = root / "target" / "doc"
    candidates = sorted(docdir.glob("*.json"))
    if not candidates:
        raise FileNotFoundError("no rustdoc JSON produced")
    return json.loads(candidates[-1].read_text())


def reconcile(floor_facts: dict, rustdoc: dict):
    """Compare floor facts to rustdoc JSON. Returns an overlay dict: resolved macro-generated
    items, re-export targets, null-span flags, and floor/rustdoc disagreements."""
    fv = rustdoc.get("format_version")
    if fv not in KNOWN_FORMAT_VERSIONS:
        return {"status": "degraded",
                "reason": f"unrecognised rustdoc format_version={fv}; not reconciling"}
    index = rustdoc.get("index", {})
    overlay = {"status": "ok", "format_version": fv,
               "macro_generated": [], "reexports": [], "null_span_items": [],
               "disagreements": []}

    floor_impl_types = {(i.get("trait"), i.get("type")) for i in floor_facts.get("impls", [])}
    for item_id, item in index.items():
        name = item.get("name")
        span = item.get("span")  # null for re-exports/blanket/synthesized/macro items
        inner = item.get("inner", {})
        kind = next(iter(inner.keys()), None) if isinstance(inner, dict) else None
        if span is None and name:
            overlay["null_span_items"].append({"name": name, "kind": kind})
        if kind == "impl" and isinstance(inner.get("impl"), dict):
            tr = inner["impl"].get("trait")
            tr_name = tr.get("name") if isinstance(tr, dict) else None
            if span is None and tr_name:
                # impl with no span => blanket / synthesized / macro-generated
                overlay["macro_generated"].append({"trait": tr_name, "span": None,
                                                    "note": "no span (blanket/synth/macro)"})
        if kind == "use" or kind == "import":
            tgt = inner.get(kind, {})
            overlay["reexports"].append({"name": name,
                                         "source": tgt.get("source") if isinstance(tgt, dict) else None})

    # Disagreement: items rustdoc has that the floor's impl set lacks (likely macro-generated)
    rustdoc_impl_traits = {it["trait"] for it in overlay["macro_generated"] if it.get("trait")}
    floor_traits = {t for t, _ in floor_impl_types if t}
    only_rustdoc = sorted(rustdoc_impl_traits - floor_traits)
    if only_rustdoc:
        overlay["disagreements"].append({
            "kind": "impls_only_in_rustdoc",
            "traits": only_rustdoc,
            "note": "rustdoc sees impls the source scanner did not — likely macro-generated; "
                    "this confirms a macro-registration seam.",
        })
    return overlay


def main():
    if len(sys.argv) < 2:
        print("usage: rustdoc_overlay.py <repo_root> [orientation_dir] [package]",
              file=sys.stderr)
        return 2
    root = Path(sys.argv[1]).resolve()
    odir = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else root / ".orientation"
    package = sys.argv[3] if len(sys.argv) > 3 else None

    ok, reason = toolchain_available()
    if not ok:
        banner = {"status": "absent", "reason": reason,
                  "effect": "Floor-only artifact. Macro-expansion counts remain "
                            "`expansion_unverified`; re-export targets unresolved. This is a "
                            "correct, honest artifact — just without the semantic overlay."}
        (odir / "rustdoc_overlay.json").write_text(json.dumps(banner, indent=2))
        print(f"[overlay] DEGRADED: {reason}")
        print("[overlay] floor-only artifact stands; no overlay applied.")
        return 0

    try:
        facts = json.loads((odir / "facts.json").read_text())
        rd = run_rustdoc_json(root, package)
        overlay = reconcile(facts, rd)
    except Exception as e:
        banner = {"status": "error", "reason": str(e),
                  "effect": "Floor-only artifact stands."}
        (odir / "rustdoc_overlay.json").write_text(json.dumps(banner, indent=2))
        print(f"[overlay] ERROR ({e}); floor-only artifact stands.")
        return 0

    (odir / "rustdoc_overlay.json").write_text(json.dumps(overlay, indent=2))
    print(f"[overlay] applied (format_version={overlay.get('format_version')}); "
          f"{len(overlay.get('macro_generated', []))} macro/blanket items, "
          f"{len(overlay.get('disagreements', []))} disagreement(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
