[package]
name = "sourcetrait_nuin"
description = "Nushell internals documentation support"
version.workspace    = true
authors.workspace    = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true
homepage.workspace   = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
bitcode.workspace = true
nu-cmd-lang.workspace = true
nu-command = { workspace = true, features = ["rand"] }
nu-engine.workspace = true
nu-parser.workspace = true
nu-protocol.workspace = true
rkyv.workspace = true
serde.workspace = true
semver.workspace = true
snafu.workspace = true

sourcetrait_common.workspace = true

[package.metadata]
reign = "human"