[package]
name = "sourcetrait_nu_model"
description = "Nushell plugin providing Nu model shaping"
version.workspace    = true
authors.workspace    = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true
homepage.workspace   = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
nu-engine.workspace = true
nu-parser.workspace = true
nu-protocol.workspace = true
nu-plugin.workspace = true
semver.workspace = true
snafu.workspace = true

sourcetrait_common.workspace = true

[package.metadata]
reign = "human"