name = "empower"
tile = "empower"
version = "0.0.1"

[author]
name = "sourcetrait"
title = "SourceTrait"
email = "development@sourcetrait.com"

[provider]
name = "github"

[common]
gear = []

[desk]
gear = [
    "empwr"
]

[box]
gear = [
    "empwr"
]

