use crate::verify::{contains_cert, pem_body};

const ANCHOR: &str = "\
-----BEGIN CERTIFICATE-----
MIIBkTCCATegAwIBAgIUxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
-----END CERTIFICATE-----
";

#[test]
fn pem_body_strips_armour_and_whitespace() {
    let body = pem_body(ANCHOR);
    assert!(!body.contains("BEGIN"), "armour must be dropped");
    assert!(!body.contains('\n'), "whitespace must be dropped");
    assert!(body.starts_with("MIIBkTCCATeg"));
}

/// The bundle is REGENERATED by update-ca-trust rather than copied, so its line
/// wrapping and surrounding commentary differ from the source anchor. Comparing the
/// PEM literally would report a false negative on a perfectly good install, which is
/// exactly the wrong direction for a verification step to fail in.
#[test]
fn matches_across_different_wrapping_and_commentary() {
    let rewrapped = "\
# Some Other CA
-----BEGIN CERTIFICATE-----
AAAABBBB
-----END CERTIFICATE-----
# SourceTrait Grammar Local CA
-----BEGIN CERTIFICATE-----
MIIBkTCCATegAwIBAgIUxxxxxxxxxx
xxxxxxxxxxxxxxxxxxAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
-----END CERTIFICATE-----
";
    assert!(contains_cert(rewrapped, ANCHOR));
}

#[test]
fn reports_absence() {
    let other = "-----BEGIN CERTIFICATE-----\nZZZZ\n-----END CERTIFICATE-----\n";
    assert!(!contains_cert(other, ANCHOR));
}

#[test]
fn an_empty_anchor_never_matches() {
    assert!(!contains_cert("anything at all", ""));
    assert!(!contains_cert("", ANCHOR));
}
