[package]
name = "sourcetrait_lib_empower"
version = "0.0.1"
edition = "2024"
description = "Shared library for sourcetrait_empower"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later WITH GPL-3.0-linking-exception"
repository = "https://github.com/sourcetrait/sourcetrait_empower"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "empower", "lib"]

[dependencies]
snafu.workspace = true
sourcetrait_testing.workspace = true
xxhash-rust.workspace = true
