[package]
name = "sourcetrait_grammar_bed"
version = "0.0.0-2"
edition = "2024"
description = "Isolated nushell embedding engine for purely functional filter scripts"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_grammar"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "grammar", "nushell", "embedding"]

[dependencies]
nu-cmd-lang.workspace = true
nu-command = { workspace = true, features = ["rand"] }
nu-engine.workspace = true
nu-parser.workspace = true
nu-protocol.workspace = true
snafu.workspace = true

[dev-dependencies]
indoc.workspace = true
sourcetrait_testing.workspace = true
tempfile.workspace = true
