[package]
name = "sourcetrait_nu_plugin_model"
version = "0.0.0-1"
edition = "2024"
description = "Nu model shaping"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_grammar"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "nu", "plugin", "model"]

[dependencies]
nu-engine.workspace = true
nu-parser.workspace = true
nu-protocol.workspace = true
nu-plugin.workspace = true
semver.workspace = true
snafu.workspace = true

[dev-dependencies]
sourcetrait_testing.workspace = true

[package.metadata]
reign = "human"